server:
  port: 7002
eureka:
  instance:
    hostname: localhost
#    hostname: eureka7002.com

  client:
#    false表示不向注册中心注册自己
    register-with-eureka: false
#    false表示自己端就是注册中心，职责是维护服务实例，不需要检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/ #集群版

#  this.serviceUrl.put("defaultZone", "http://localhost:8761/eureka/");

#spring:
##  application:
##    name: cloud-eureka-server
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
#    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
#    url: jdbc:mysql://localhost:3306/si_system?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: root
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.lc.homepage.entity #所有entity别名类所在的包
