server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名就行路由
      routes:
        - id: payment_routh #payment_route 路由id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: userGet://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址，通过网关实现负载均衡
          predicates:
            - Path=/payment/userGet/** #断言，路径相匹配的进行路由
#            - After=2021-02-24T15:20:48.284+08:00[Asia/Shanghai]#在此时间之后
            - Cookie=username,xxyy #键值对
        - id: payment_routh2 #payment_route 路由id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址，通过网关实现负载均衡
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

